config/routes.rb
Rails.application.routes.draw do
  root to: 'twits#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :twits
  resources :sessions
end

app/models/twit.rb
class Twit < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email
  has_many :twits
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_filter :authorize
def index
    @twits = Twit.all.order('created_at DESC').first(10)
  end

  def new
    @twit = Twit.new
  end

  def create
    # @user = User.find(params[:user_id])
    @twit = Twit.create(twit_params)
    if @twit.valid?
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Twitted!" }
        format.js
      end
    else
      render 'new'
    end
  end

  def show
    @twit = Twit.find(params[:id])
  end

  def destroy
    @twit = Twit.find(params[:id])
    @twit.destroy
    redirect_to root_path, notice: "Twit Deleted.."
  end

private
  def twit_params
    params.require(:twit).permit(:content, :user_id).merge(:user_id => current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "Profile Updated"
    else
      render 'show'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "Account has been deleted! See you never!"
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <% if current_user %>
    Welcome, <%= current_user.name %>! |
    <%= link_to "Twit Feed", root_path %> |
    <%= link_to "New Twit", new_twit_path, id: "new_twit", remote:true %> |
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %><br><br>
  <%= flash[:alert] %>
  <%= flash[:notice] %>

<%= yield %>
</div>
</body>
</html>

app/views/twits/_form.html.erb
<%= form_for @twit, id: "twit_form", remote: true do |f| %>
  <p>Feed me your thoughts:</p>
  <%= f.text_area :content %><br>
  <%= f.submit "Twit!" %>
<% end %>

app/views/twits/_twit.html.erb
<li><%= link_to "#{twit.user.name}", user_path(twit.user_id) %> says:
<%= twit.content %></li><br>

app/views/twits/create.js.erb
$('form').remove();
$('#new_twit').show();
$('#twit').prepend('<%= j render(@twit) %>');

app/views/twits/index.html.erb
<h1>All Twits</h1>

<ul id="twit">
  <% @twits.each do |twit| %>
    <li><%= link_to "#{twit.user.name}", user_path(twit.user_id) %> says:
      <%= twit.content %></li><br>
  <% end %>
</ul>

app/views/twits/new.html.erb
<h1>Twit!</h1>

<%= render 'form' %>

app/views/twits/new.js.erb
$('#new_twit').hide().after(' <%= j render "form" %>');

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'layouts/errors', object: @user %>
<%= render 'form' %>

app/views/users/show.html.erb
<br>
<%= "#{@user.name}" %>
<br>
<%= "#{@user.email}" %>